spring:
  application:
    name: ConversationalAI4J Demo

server:
  port: 8080

# Docker-specific overrides only
app:
  ollama-base-url: http://ollama:11434  # Use Docker service name instead of localhost

# Simple logging - no duplicates
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
