name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for SonarCloud
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'
          cache-dependency-path: |
            conversational-ai4j-*/*.gradle*
            conversational-ai4j-*/**/gradle-wrapper.properties
      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run tests
        run: ./gradlew test jacocoTestReport sonar --continue --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: 'Test Results'
          path: '**/build/test-results/test/*.xml'
          reporter: 'java-junit'
          fail-on-error: false

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build --no-cache -t conversationalai4j-test .
      - name: Verify Docker image
        run: docker images conversationalai4j-test
